services:
  recuerdame:
    image: recuerdame
    container_name: RecuerdameContenedor
    build:
      context: .
      dockerfile: Recuerdame/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RecuerdameDb;User Id=sa;Password=PasswordDev123!;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    restart: always

  sqlserver:
    container_name: RecuerdameSqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PasswordDev123!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"          # Solo Nginx expone puertos al host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - app-network
    depends_on:
      dotnet-api:
        condition: service_healthy
    restart: unless-stopped

volumes:
  sql_data:

